export const CHANGEINPUT = 'CHANGEINPUT';

export const CHANGESTATUS = 'CHANGESTATUS';

export const CHANGESOUND = 'CHANGESOUND';

export const PLAYSOUND = 'PLAYSOUND';

export const STARTCLICKING = 'STARTCLICKING';

export const STOPCLICKING = 'STOPCLICKING';
